

import React from 'react';

export enum ViewName {
  Dashboard = 'Dashboard',
  AudienceModeling = 'Audience Modeling',
  OperatorBuilder = 'Operator Builder',
  ContentPlanner = 'Content Planner',
  FeedbackSimulator = 'Feedback Simulator',
  AuditTool = 'Audit Tool',
  Methodology = 'Methodology',
  AdminPanel = 'Admin Panel',
  Calendar = 'Calendar',
  Settings = 'Settings', 
  DataAnalyzer = 'Data Analyzer',
  ContentLibrary = 'Content Library',
  TeamChat = 'Team Chat',
  SocialPoster = 'Social Poster',
}

// For pages within the authentication flow (before user is logged in)
export type AuthViewType = 'home' | 'login' | 'register' | 'features' | 'pricing' | 'documentation' | 'about' | 'contact' | 'privacy' | 'terms';

export enum RoleName {
    Free = 'Free',
    Essentials = 'Essentials',
    Admin = 'Admin',
}

export interface RoleType {
    id: string; // uuid
    name: RoleName;
    max_personas: number;
    max_ai_uses_monthly: number;
    price_monthly: number;
    price_yearly: number;
    features: string[]; // Stored as TEXT[] in postgres
    created_at?: string;
    updated_at?: string;
}

// Represents the enriched User object with profile and role details
export interface UserProfile extends User {
  role: RoleType;
  ai_usage_count_monthly: number;
  assigned_ai_model_text?: string;
  assigned_ai_model_image?: string;
}

// Represents a Supabase user, with profile data potentially merged in
export interface User {
  id: string; // Supabase user ID (UUID)
  email?: string;
  name?: string; // from user_metadata or profiles table
  walletAddress?: string; // from profiles table
  teamMembers?: string[]; // from profiles table
  role_name?: RoleName;
}

// Represents a row from the admin_users_view for the Admin Panel
export interface AdminUserView {
  id: string;
  email?: string;
  name?: string;
  role_name: RoleName;
  ai_usage_count_monthly: number;
  assigned_ai_model_text?: string;
  assigned_ai_model_image?: string;
  updated_at: string;
}


export interface NavItem {
  label: string;
  viewName?: ViewName;
  icon?: React.ReactNode;
  children?: NavItem[];
  isAdminOnly?: boolean;
}

export type RSTTraitLevel = 'Not Assessed' | 'Low' | 'Medium' | 'High';

export interface RSTProfile {
  bas: RSTTraitLevel; // Behavioral Approach System
  bis: RSTTraitLevel; // Behavioral Inhibition System
  fffs: RSTTraitLevel; // Fight-Flight-Freeze System
}

export interface Persona {
  id: number; // DB id
  user_id: string; // Foreign key to Supabase user
  name: string;
  demographics?: string;
  psychographics?: string;
  initial_beliefs?: string;
  vulnerabilities?: string[];
  avatar_url?: string;
  rst_profile?: RSTProfile; 
  created_at?: string;
  updated_at?: string;
}

// Represents a persona from the imported library (Nemotron-style)
export interface LibraryPersona {
  id: string;
  name: string;
  occupation: string;
  age: number;
  personality: string;
  hobbies: string[];
  relationship_status: string;
  values: string[];
  fears: string[];
  goals: string[];
}


export interface Operator {
  id: number; // DB id
  user_id: string; // Foreign key to Supabase user
  name: string;
  target_audience_id: number; // Foreign key to Persona
  type: 'Hope' | 'Fear' | 'Belonging' | 'Exclusivity' | 'Curiosity' | 'Authority' | 'Novelty' | 'Pride' | 'Nostalgia' | 'Convenience' | 'Custom';
  conditioned_stimulus: string;
  unconditioned_stimulus:string;
  desired_conditioned_response: string;
  reinforcement_loop: string;
  created_at?: string;
  updated_at?: string;
}

export type MediaType = 'none' | 'image' | 'video';
export type ImageSourceType = 'generate' | 'upload' | 'library';

export interface PlatformContentDetail {
  content: string;
  hashtags: string[];
  mediaType: MediaType;
  subject?: string; 

  imageSourceType?: ImageSourceType; 
  imagePrompt?: string; 
  uploadedImageFile?: File; // Transient state for uploads
  uploadedImageBase64?: string;
  libraryAssetId?: string; // Changed to string for uuid
  memeText?: string;
  processedImageUrl?: string; 

  videoIdea?: string;

  fontFamily?: string;
  fontColor?: string; 
  aiSuggestedFontCategory?: string;
}

export type PlatformContentMap = Record<string, PlatformContentDetail>;

export interface ContentDraft {
  id: string; // uuid, generated by DB
  user_id: string; // Foreign key to Supabase user
  operator_id: number; // Foreign key to Operator
  persona_id: number; // Foreign key to Persona
  key_message?: string;
  custom_prompt: string;
  platform_contents: PlatformContentMap;
  platform_media_overrides?: Record<string, MediaType | 'global'>;
  created_at?: string;
  updated_at?: string;
}

export interface FeedbackSimulationResult {
  sentiment: {
    positive: number;
    neutral: number;
    negative: number;
  };
  engagementForecast: 'Low' | 'Medium' | 'High';
  potentialRisks?: string[];
}

export interface AuditStep {
  id: string;
  title: string;
  description: string;
  content?: string;
  isCompleted: boolean;
  riskAlerts?: string[];
}

export enum AiProviderType {
  Gemini = 'Gemini',
  OpenAI = 'OpenAI',
  Anthropic = 'Anthropic',
  Groq = 'Groq',
  Deepseek = 'Deepseek',
  Qwen = 'Qwen',
  Openrouter = 'Openrouter',
  MistralAI = 'MistralAI',
  Placeholder = 'Placeholder (Not Implemented)',
}

export interface AiProviderModelSet {
  text: string[];
  image?: string[];
  chat?: string[];
}
export interface AiProviderConfig {
  id: AiProviderType;
  name: string;
  api_key: string | null; 
  is_enabled: boolean;
  models: AiProviderModelSet;
  notes?: string;
  base_url?: string;
  updated_at?: string;
}

export type AiProviderConfigForExport = Omit<AiProviderConfig, 'api_key'> & { apiKey?: null };


export interface GroundingChunk {
  web?: {
    uri?: string;
    title?: string;
  };
  retrievedContext?: {
    uri?: string;
    title?: string;
  };
}

export type ScheduledPostStatus = 'Scheduled' | 'Publishing' | 'Published' | 'Failed' | 'Missed' | 'Cancelled';

export interface ScheduledPostResource {
  contentDraftId: string;
  platformKey: string;
  status: ScheduledPostStatus;
  notes?: string;
  personaId: number;
  operatorId: number;
  last_attempted_at?: string;
  error_message?: string;
}

export interface ScheduledPost {
  id: string; 
  db_id: number;
  title: string;
  start: Date; 
  end: Date;   
  allDay?: boolean;
  resource: ScheduledPostResource;
}

export interface ScheduledPostDbRow {
    id: number;
    user_id: string;
    content_draft_id: string;
    platform_key: string;
    status: ScheduledPostStatus;
    notes?: string;
    scheduled_at: string; // ISO string
    error_message?: string;
    last_attempted_at?: string;
}

export enum SocialPlatformType {
  X = 'X', 
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  LinkedIn = 'LinkedIn',
  Pinterest = 'Pinterest',
  TikTok = 'TikTok',
  YouTube = 'YouTube',
}

export interface ConnectedAccount {
  id: number;
  user_id: string;
  platform: SocialPlatformType;
  accountId: string; 
  displayName: string; 
  profileImageUrl?: string; 
  connectedAt: string; 
}

export interface ContentLibraryAsset {
  id: string; // uuid
  user_id: string;
  name: string;
  type: 'image' | 'video'; 
  storage_path: string; // e.g., 'public/user-id/filename.png'
  file_name: string;
  file_type: string; 
  size: number; 
  tags?: string[];
  uploaded_at: string; 
  publicUrl?: string; // Only for client-side generation, not in DB
}

export interface ChatMessageAttachment {
  name: string;
  type: string; 
  size: number; 
  publicUrl: string; 
}

export interface ChatMessage {
  id: string; // Client-side generated, hence string
  channel_id: string;
  user_id: string;
  sender_name: string; 
  created_at: string; 
  text?: string;
  attachment?: ChatMessageAttachment;
}

export interface CustomChannel {
  id: string; // Client-side generated, hence string
  uuid: string;
  name: string; 
  created_by: string;
  created_at: string; 
}

export interface DbSchema {
  profiles: {
    id: string;
    name: string;
    wallet_address: string;
    team_members: string[];
    ai_usage_count_monthly: number;
    assigned_ai_model_text?: string;
    assigned_ai_model_image?: string;
    updated_at: string;
  };
  user_roles: {
      id: string;
      user_id: string;
      role_id: string;
      assigned_at: string;
  };
  ai_provider_global_configs: AiProviderConfig;
  personas: Persona;
  operators: Operator;
  content_drafts: ContentDraft;
  content_library_assets: ContentLibraryAsset;
  scheduled_posts: ScheduledPostDbRow;
  connected_accounts: ConnectedAccount;
  role_types: RoleType;
}

export interface AISuggestionRequest {
  prompt: string;
  context?: string;
}

export interface AIParsedJsonResponse<T> {
  data: T | null;
  error?: string;
}

export interface ToastMessage {
  id: string;
  message: string;
  type: 'success' | 'error' | 'info';
  duration?: number;
}

export interface ToastContextType {
  showToast: (message: string, type: ToastMessage['type'], duration?: number) => void;
}
